services:
  trapigo:
    build:
    # TODO: check if should add compose.dev.yml for DEV overrides like target: dev, and security_opt: seccomp:unconfined, etc.
      target: dev # Overrides the target to use the Delve stage
    ports:
      - "40000:40000"  # Delve Debugger port for Trapigo
    environment:
      - BASE_URL=http://localhost
      - PORT=80
      - LOG_LEVEL=DEBUG
    security_opt:
      - "seccomp:unconfined" # Allows Delve to inject breakpoints into the OS process

