services:
  trapigo:
    build:
    # TODO: check if should add compose.dev.yml for DEV overrides like target: dev, and security_opt: seccomp:unconfined, etc.
      target: dev # Overrides the target to use the Delve stage
    ports:
      - "80:80"        # Main gateway entrypoint (http://localhost/)
      - "8080:8080"    # Admin Dashboard / API UI (http://localhost:8080)
      - "40000:40000"  # Delve Debugger port for Trapigo
    environment:
      - BASE_URL=http://localhost
      - PORT=80
      # --- Downstream Timeouts (Client to Trapigo) ---
      - READ_HEADER_TIMEOUT=5     # Crucial for Slowloris protection
      - READ_TIMEOUT=0            # 0 means disabled; let the handler/stream control body uploads
      - WRITE_TIMEOUT=0           # 0 means disabled; allows streaming and slow clients
      - IDLE_TIMEOUT=180          # 3 minutes; good balance for keep-alive connection reuse
      # --- Upstream Timeouts (Trapigo to Backends) ---
      - BACKEND_DIAL_TIMEOUT=5    # Max time to connect to a backend service container
      - BACKEND_TIMEOUT=30        # Max time a backend has to process and return a response
    security_opt:
      - "seccomp:unconfined" # Allows Delve to inject breakpoints into the OS process

