http:
  # Simple Global Rate Limiting Configuration. Rate Limiting in production is better configurable per service
  rate-limit:
    enabled: true
    token-bucket:
      capacity: 100
      refill-rate: 100
      refill-interval-in-seconds: 60

  routers:
    users-router:
      path-prefix: /api/v1/users
      service: users-service

    go-orders-router:
      path-prefix: /api/v1/go-orders
      service: go-order-service

    dotnet10aot-orders-router:
      path-prefix: /api/v1/dotnet10-aot-orders
      service: dotnet10aot-order-service

  services:
    users-service:
      load-balancer:
        servers:
          - url: http://app-one:8080

    go-order-service:
      load-balancer:
        servers:
          - url: http://go-order-service:8080

    orders-service:
      load-balancer:
        servers:
          - url: http://app-two:8080

    dotnet10aot-order-service:
      load-balancer:
        servers:
          - url: http://dotnet10aot-order-service:8080